### ISSUE TITLE
Optimize Home Page 

### ISSUE THREAD

**Issue by chaitanyakatore** [ankitrout2903/Swingyy#7] opened 2023-09-30 20:46 UTC
Assign me this issue so I can perform following task:
-  Better UI for home page
-  Users profile picture

**Comment by ankitrout2903** [comment] 2023-09-30 21:06
>  Assign me this issue so I can perform following task:
> -  Better UI for home page
> -  Dark Mode 
> -  Users profile picture 

Yess Buddy go ahead happy hacking 😉. 🤠.

**Comment by chaitanyakatore** [comment] 2023-10-01 13:11
hello Aniket I am working on this issue but I am facing some difficulty because I am not familiar
with backend so will you please tell me what command should I type so backend server also work and I can run whole project and see the home page

**Comment by HeetVekariya** [comment] 2023-10-01 13:41
I would say all things are written in the README.md file.
So you can check it from there.

## Frontend:
```cd frontend```
```npm install```


## Backend:
```cd ../backend```
```npm install```

**Comment by HeetVekariya** [comment] 2023-10-01 13:44
All steps to run the code is shown in the README.md file.

You can check the **Step: 5** in the installation steps

**Comment by HeetVekariya** [comment] 2023-10-01 15:04
@ankitrout2903 Thank you for assigning me.
But what i have to do, it is already assigned to @chaitanyakatore

**Comment by ankitrout2903** [comment] 2023-10-01 15:27
What you to to do is goto server folder then run npm install
Then non start
Then goto client folder run npm I and then non start

Use dotevv variables for you MySQL and use firebaseconfig for running firebase in front end use if you want my credentials you can contact my discord

**Comment by HeetVekariya** [comment] 2023-10-01 15:30
I am saying that as already the issue is assigned to @chaitanyakatore , i will help him if required

**Comment by chaitanyakatore** [comment] 2023-10-01 17:10
- @HeetVekariya I was trying to add NavBar and footer to the home page 
- also when we go to home page we see you login as gmail but we can make it profile photo and add the user name to it
you can work on this issue if you want I was unable to understand the backend when I did the changes I was unable to see the home page because it's showing the gmail login page only when I type npm start
I think I need to add the MySQL server

**Comment by HeetVekariya** [comment] 2023-10-01 17:15
Can you send me the screen shorts, if possible

**Comment by ankitrout2903** [comment] 2023-10-01 17:20
https://youtu.be/jpTh_Csh3Lo?feature=shared
Watch this video.

**Comment by HeetVekariya** [comment] 2023-10-02 07:37
@ankitrout2903 sorry to say that, but currently i am not working for this issue.
So you can remove me assignee for now such that others can contribute to this.

When i will be free from other work i will work on this. :+1:

**Comment by chaitanyakatore** [comment] 2023-10-02 19:25
> What you to to do is goto server folder then run npm install Then non start Then goto client folder run npm I and then non start
> 
> Use dotevv variables for you MySQL and use firebaseconfig for running firebase in front end use if you want my credentials you can contact my discord

give me the discord

**Comment by ankitrout2903** [comment] 2023-10-02 19:37
https://youtu.be/jpTh_Csh3Lo?feature=shared
ankitrout2903 discord I'd
It's also in my GitHub

**Comment by chaitanyakatore** [comment] 2023-10-06 07:25
@ankitrout2903 I messaged you on discord
please check

**Comment by ankitrout2903** [comment] 2023-10-06 07:26
>  Assign me this issue so I can perform following task:
> -  Better UI for home page
> -  Users profile picture 

Yess bro go ahead do and give a pr

**Closed as completed** 2023-10-07 13:58 UTC
Labels: enhancement, hacktoberfest
